version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hockey_postgres_db
    restart: always
    environment:
      POSTGRES_USER: hockey_user
      POSTGRES_PASSWORD: hockey_password
      POSTGRES_DB: hockey_tickets
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: